# Author: Adam Binch
# email: adambinch@gmail.com

# include:                    boolean: you can turn a model on or off by setting include: 1 or include: 0, respectively
# pole_nx                     integer: number of poles aligned with the x-axis
# pole_ny                     integer: number of poles aligned with the y-axis (keep fixed at pole_ny: 5, if you want the canopy to fit)
# pole_dx                     float: distance between poles aligned with the x-axis (meters)
# pole_dy                     float: distance between poles aligned with the y-axis (meters) (keep fixed at pole_dy: 1.35, if you want the canopy to fit)
# pole_xoffset                float: sets the position of the poles along the x-axis (meters)
# pole_yoffset                float: sets the position of the poles along the y-axis (meters)
# arch_nx                     integer: number of arches 
# arch_dx                     float: distance between arches (meters)
# arch_xoffset                float: sets the position of the arches along the x-axis (meters)

# note: if you don't want the polytunnel to have a canopy set arch_nx: 0
# note: if you change the world name you will also have to change it in the launch file ../launch/world.launch (or make another launch file).


- world_name: 'riseholme.world'     

- polytunnel:
  - include: 1     # polytunnel 1
    pole_nx: 9
    pole_ny: 5
    pole_dx: 3
    pole_dy: 1.35
    pole_xoffset: 7
    pole_yoffset: -6.75
    arch_nx: 7
    arch_dx: 4.333
    arch_xoffset: 6

  - include: 1     # polytunnel 2
    pole_nx: 9
    pole_ny: 5
    pole_dx: 3
    pole_dy: 1.35
    pole_xoffset: 7
    pole_yoffset: 1.35
    arch_nx: 7
    arch_dx: 4.333
    arch_xoffset: 6

- riseholme_enclosure:
  - include: 1
    xpose: 10     
    ypose: -1.35

- food_handling_shed:
  - include: 1
    xpose: -8.9 
    ypose: -1.16


