
# Constant for float type argument
string FLOAT_TYPE="____float____"
# Constant for int type argument
string INT_TYPE="____int____"
# Constant for ros time type argument
string TIME_TYPE="____time____"
# Constant for ros duration type argument
string DURATION_TYPE="____duration____"
# Constant for bool type
string BOOL_TYPE="____bool____"
# Constant for string type
string STRING_TYPE="____str____"

#goal definition
strands_executive_msgs/Task task
duration min_load_duration
duration max_load_duration
duration min_unload_duration
duration max_unload_duration
---
#result definition
int64 task_id
bool success
---
#feedback
int64 task_id
string mode
string closest_node
string route
