global_costmap:
  global_frame: world
#  robot_base_frame: base_link
  update_frequency: 5.0
  static_map: true
  robot_base_frame: actor00/base_link
#  obstacle_layer:
#    laser_scan_sensor:
#      sensor_frame: actor00/hokuyo
