local_costmap:
  global_frame: actor00/odom
  robot_base_frame: actor00/base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.05
#  obstacle_layer: 
#    laser_scan_sensor:
#      sensor_frame: 'actor00/hokuyo'

plugins:
  - {name: laser_scan_sensor,           type: "costmap_2d::ObstacleLayer"}
#  - {name: inflation,                 type: "costmap_2d::InflationLayer"}
