footprint: [[0.25, 0.175], [0.25, -0.175], [-0.25, -0.175], [-0.25, 0.175]]

obstacle_layer:
  obstacle_range: 2.5
  raytrace_range: 3.0

#  robot_radius: ir_of_robot
  inflation_radius: 0.55

  observation_sources: laser_scan_sensor #point_cloud2_sensor

  laser_scan_sensor: {sensor_frame: actor00/hokuyo, data_type: LaserScan, topic: actor00/scan, marking: true, clearing: true}

#  point_cloud2_sensor: {sensor_frame: base_link, data_type: PointCloud2, topic: obst_cloud, marking: true, clearing: true}

